//Copyright(C) 2014, ShareThis, Inc. All rights reserved
//This class was generated by com.sharethis.common.utils.codegen.SQLTable2ClassWriter
//Schema: AdQualityAdGroupsView
//Date: Aug 12, 2014 4:16:18 PM
//
package com.sharethis.adquality.dao;

public class AdQualityAdGroupsViewDAO extends com.sharethis.common.dao.BaseDAO {
	public static String TABLE_NAME="AdQualityAdGroupsView";
	public static final String SELECT = 
	"select adGroupId,name,flags from AdQualityAdGroupsView";
	public static final String SELECT_EX = 
	"select adGroupId,name,flags from %s";
	public static final String INSERT = 
	"insert into AdQualityAdGroupsView(adGroupId,name,flags)" + 
	"values(%d,'%s',%d)";
	public static final String INSERT_EX = 
	"insert into %s(adGroupId,name,flags)" + 
	"values(%d,'%s',%d)";
	public static final String INSERT_BATCH = 
	"insert into AdQualityAdGroupsView(adGroupId,name,flags) values(?,?,?)";

	//Member variables
	protected long adGroupId;
	protected String name;
	protected int flags;

	//Get methods
	public long getAdGroupId() {return adGroupId;}
	public String getName() {return name;}
	public int getFlags() {return flags;}

	//Set methods
	public void setAdGroupId(long val) {this.adGroupId = val;}
	public void setName(String val) {this.name = val;}
	public void setFlags(int val) {this.flags = val;}

	//SQL interfaces
	public static AdQualityAdGroupsViewDAO fromResultSet(java.sql.ResultSet rs) throws java.sql.SQLException
	{
	int idx = 1;
	AdQualityAdGroupsViewDAO entry = new AdQualityAdGroupsViewDAO();
	entry.adGroupId = rs.getLong(idx++);
	entry.name = rs.getString(idx++);
	entry.flags = rs.getInt(idx++);
	return entry;
	}

	public static java.util.List<AdQualityAdGroupsViewDAO> loadAll(java.sql.ResultSet rs) throws java.sql.SQLException
	{
	java.util.List<AdQualityAdGroupsViewDAO> list = new java.util.ArrayList<AdQualityAdGroupsViewDAO>();
	while (rs.next()) {
	AdQualityAdGroupsViewDAO entry = AdQualityAdGroupsViewDAO.fromResultSet(rs);
	list.add(entry);
	}
	return list;
	}

	public static java.util.List<AdQualityAdGroupsViewDAO> readByQuery(com.sharethis.common.sql.DBConnect conn, String query, com.sharethis.common.state.RuntimeState rs) throws java.sql.SQLException
	{
	rs.message = query;
	java.sql.Statement s = conn.queryWithResults(query);
	java.util.List<AdQualityAdGroupsViewDAO> list = loadAll(s.getResultSet());
	s.close();
	return list;
	}


	//Serialization
	public String toString()
	{
	StringBuffer sb = new StringBuffer();
	sb.append(this.adGroupId);
	sb.append(com.sharethis.common.dao.BaseDAO.DB_FILE_FIELD_DELIMITER);
	sb.append(this.name);
	sb.append(com.sharethis.common.dao.BaseDAO.DB_FILE_FIELD_DELIMITER);
	sb.append(this.flags);
	sb.append(com.sharethis.common.dao.BaseDAO.DB_FILE_FIELD_DELIMITER);
	return sb.toString();
	}
}
