//Copyright(C) 2014, ShareThis, Inc. All rights reserved
//This class was generated by com.sharethis.common.utils.codegen.JSON2ClassWriter
//Source: /Users/wahid/Projects/adoptimization/adquality/json/ias_campaign_viewability_report.txt
//Date: Aug 26, 2014 3:20:16 PM
//
package com.sharethis.iasapi;

import java.io.StringReader;

public class IasCampaignViewabiltyReport {
public int recordCount;
public java.util.List<Viewability> viewability;
public java.lang.String query;
public java.lang.String path;
public int executionTimeMS;

public static IasCampaignViewabiltyReport fromJson(java.io.File source) throws java.io.IOException {
com.google.gson.stream.JsonReader reader = new com.google.gson.stream.JsonReader(new java.io.InputStreamReader(new java.io.FileInputStream(source)));
com.google.gson.Gson gson = new com.google.gson.Gson();
return gson.fromJson(reader, IasCampaignViewabiltyReport.class);
}

public static IasCampaignViewabiltyReport fromJson(String source) throws java.io.IOException {
com.google.gson.stream.JsonReader reader = new com.google.gson.stream.JsonReader(new StringReader(source));
com.google.gson.Gson gson = new com.google.gson.Gson();
return gson.fromJson(reader, IasCampaignViewabiltyReport.class);
}

public String toJson(boolean htmlEscaping) {
com.google.gson.GsonBuilder builder = new com.google.gson.GsonBuilder();
if(!htmlEscaping)
builder.disableHtmlEscaping();
com.google.gson.Gson gson = builder.create();
return gson.toJson(this);
}

public static class Viewability {
public java.lang.String campaignName;
public java.lang.String inView1sPct;
public java.lang.String campaignId;
public java.lang.String outOfViewPct;
public java.lang.String inView15sPct;
public java.lang.String measuredImps;
public java.lang.String unmeasuredImps;
public java.lang.String totalImpressions;
public java.lang.String timeOnPage;
public java.lang.String inViewTime;
public java.lang.String inView5sPct;
public java.lang.String suspiciousPct;
public java.lang.String inViewLoadPct;
public java.lang.String viewableRate;
public java.lang.String totalSampled;
public java.lang.String neverInViewPct;
public java.lang.String qDataImps;
public java.lang.String measuredRate;
}//Viewability

}//IasCampaignViewabiltyReport
